name: Run tests

on:
  push:
    branches: 
        - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies (editable)
      working-directory: opencompass
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run selected unit tests
      working-directory: opencompass
      env:
        PYTHONPATH: ${{ github.workspace }}/opencompass
      run: |
        echo "Running openicl tests..."
        python -m unittest discover -s tests/openicl -p "test_*.py"
        echo "Running prompt tests..."
        python -m unittest discover -s tests/prompt -p "test_*.py"
        echo "Running humaneval dataset test..."
        python -m unittest tests/dataset/test_humaneval.py